#!/bin/bash

. /home/martin/git/watch-scripts/common_functions

series_path=/home/martin/series/

set_ifs

for i in $(get_all_episodes | sort -n); do
  print_name_of_series
  echo ": $i"
done | get_first_episode | print_full_filename
get_episodes_from_next_links

restore_ifs
