#!/bin/bash

test -z "$1" && exit 1

mkfifo /tmp/mpv_control > /dev/null 2>&1

if [[ "$1" == "stop" ]]; then
  echo "quit_watch_later" > /tmp/mpv_control
  exit 0
fi

if [[ "$1" == "pause" ]]; then
  echo "pause" > /tmp/mpv_control
  exit 0
fi

if [[ -f "$1" ]]; then
  fullfile=$1
elif [[ "$1" == http* ]]; then
  fullfile=$1
else
  file=$(echo $1 | sed -e "s/\[/\\\[/g" -e "s/\]/\\\]/g")
  fullfile=$(find /home/martin/series/ -name "$file" | head -n 1)
  test -f "$fullfile" || exit 1
fi

export DISPLAY=:0.0
/usr/local/bin/control-spotify pause
mpv "$fullfile" --x11-name tv --alang=jpn --input-file /tmp/mpv_control < /dev/null > /dev/null 2>&1 &
