#!/bin/bash

test -z "$1" && exit 1

export DISPLAY=:0.0
mkfifo /tmp/mpv_control > /dev/null 2>&1
/usr/local/bin/control-spotify pause
mpv "$1" --name tv --input-file /tmp/mpv_control < /dev/null > /dev/null 2>&1 &
